name: Build und Push zur GitHub Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: Image deployen
        default: "nein"
        type: choice
        options:
          - "ja"
          - "nein"
env:
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

jobs:
  prepare_env:
    name: Prepare Enviroment
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        id: myvar
        run: |
          echo "deploy=${{ inputs.deploy || 'weissnicht'}}"" >> "$GITHUB_OUTPUT"
    outputs:
      deploy: ${{ steps.myvar.outputs.deploy }}
 
  Job_2:
    name: Job 2
    if: ${{ needs.prepare_env.outputs.deploy == 'ja' }}
    runs-on: ubuntu-latest
    needs: [prepare_env]
    steps:
      - name: Test
        env:
          GITHUB_JSON: ${{ toJSON(github) }}
          NEEDS_JSON: ${{ toJSON(needs) }}
        run: |
          echo ${GITHUB_JSON}
          echo ${NEEDS_JSON}

  Job_3:
    name: Job 3
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    needs: [Job_2]
    steps:
      - name: Test
        run: |
          ls -la
