name: Build und Push zur GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  oracle_start:
    name: Prepare
    container: docker:dind
    runs-on: self-hosted
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4
      - name: Test
        run: ls -la      
      - name: Oracle
        run: chmod +x .github/oracle_start_script18.sh && .github/oracle_start_script18.sh
        
  build_app:
    name: Anwendung Bauen
    container: gradle:7-jdk8
    runs-on: self-hosted
    
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test1
        run: ls -la      
