name: Build und Push zur GitHub Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: Image deployen
        default: "nein"
        type: choice
        options:
          - "ja"
          - "nein"
env:
  DEPLOY: ${{ github.event.inputs.deploy || 'vielleicht' }}
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

jobs:
  Job_1:
    name: Job 1
    runs-on: ubuntu-latest
    env:
      VARS_JSON: ${{ toJSON(github) }}
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4
      - name: Test
        run: |
          ls -la
          echo Deploy: ${{ inputs.deploy }}
          echo Deploy: ${DEPLOY}
          echo "${VARS_JSON}"

  Job_2:
    name: Job 2
    if: ${{ github.env.DEPLOY == 'ja' }}
    runs-on: ubuntu-latest
    needs: [Job_1]
    steps:
      - name: Test
        run: |
          ls -la

  Job_3:
    name: Job 3
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    needs: [Job_2]
    steps:
      - name: Test
        run: |
          ls -la
