name: Build und Push zur GitHub Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        description: Image deployen
        default: "nein"
        type: choice
        options:
          - "ja"
          - "nein"
env:
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")
  ORACLE_DB: oracle-xe.arc-runners:1521/xe

jobs:
  prepare_env:
    name: Prepare Enviroment
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        id: var
        run: |
          echo "deploy=${{ inputs.deploy || 'ja'}}" >> "$GITHUB_OUTPUT"
          echo "ORACLE_CONNECT_STRING=system/oracle@//$ORACLE_DB" >> "$GITHUB_OUTPUT"
    outputs:
      deploy: ${{ steps.var.outputs.deploy }}
      oracle_connection: ${{ steps.var.outputs.ORACLE_CONNECT_STRING }}
 
  Job_2:
    name: Job 2
    if: ${{ needs.prepare_env.outputs.deploy == 'ja' }}
    runs-on: ubuntu-latest
    needs: [prepare_env]
    steps:
      - name: Test
        env:
          GITHUB_JSON: ${{ toJSON(github) }}
          NEEDS_JSON: ${{ toJSON(needs) }}
        run: |
          echo ${{ needs.prepare_env.outputs.oracle_connection }}
          echo ${NEEDS_JSON}

  Job_3:
    name: Job 3
    if: ${{ !failure() && !cancelled() }}
    runs-on: ubuntu-latest
    needs: [Job_2]
    steps:
      - name: Test
        run: |
          ls -la
