name: Build und Push zur GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  oracle_start:
    name: Prepare
    container: docker:dind
    runs-on: self-hosted
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4
      - name: Test
        run: ls -la      
      - name: Oracle
        run: chmod +x .github/oracle_start_script18.sh && .github/oracle_start_script18.sh start
        
  build_app:
    name: Anwendung Bauen
    container: gradle:7-jdk8
    runs-on: self-hosted
    needs: [oracle_start]
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test
        run: |
          mkdir -p  test/report/
          cp -R build/doc/junit/AllKasse20Tests/ test/report/
          ls -la  test/report/
  
  test_report:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          ls -la  test/report/
      - name: Test Report1
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests
          path: 'test/report/AllKasse20Tests/*.xml'
          reporter: java-junit

